# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
jobs:
  include:
    - stage: Dependencies
      julia: 1.3
      script: julia --project
        using Pkg
        Pkg.add(https://github.com/korbinian90/RomeoApp.jl)
      after_success: skip
