name = "CompileMRI"
uuid = "4e98bb4c-fe77-4837-9a5a-17415e248a88"
authors = ["Korbinian Eckstein"]
version = "0.2.3"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
PackageCompiler = "1"
julia = "1.5"
