name = "CompileMRI"
uuid = "4e98bb4c-fe77-4837-9a5a-17415e248a88"
authors = ["Korbinian Eckstein"]
version = "0.1.0"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"

[compat]
PackageCompiler = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
