name: Compile Zip
on:
  - push
jobs:
  main:
    name: Julia 1.7 - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, 'zip')"
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
    steps:
      - run: ls
      - run: mkdir compile
      - run: Compress-Archive -Path 'compile' -DestinationPath 'compiled.zip'
      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: mritools_${{ runner.os }}_TODO.zip
          path: compiled.zip
