name: Release
on:
  - push
jobs:
  release:
    runs-on: ubuntu_latest
    steps:
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: test2
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN:  ${{ github.token }}